# Generated by Django 4.1 on 2025-01-14 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('locationname', models.CharField(max_length=50)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_district')),
            ],
        ),
    ]
