# Generated by Django 4.1 on 2025-01-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_tbl_ocation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_ocation',
            new_name='tbl_location',
        ),
    ]
