# Generated by Django 4.1 on 2025-01-14 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_rename_tbl_ocation_tbl_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_unit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unitname', models.CharField(max_length=50)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_district')),
            ],
        ),
    ]
