# Generated by Django 4.1 on 2025-01-17 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0001_initial'),
        ('adminapp', '0004_tbl_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('membername', models.CharField(max_length=50)),
                ('memberphoto', models.ImageField(upload_to='')),
                ('licensephoto', models.ImageField(upload_to='')),
                ('mobile_no', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.login')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_unit')),
            ],
        ),
    ]
