# Generated by Django 4.1 on 2025-01-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_tbl_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_member',
            name='mobile_no',
            field=models.BigIntegerField(),
        ),
    ]
