# Generated by Django 4.1 on 2025-01-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_tbl_member_mobile_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_welfare',
            fields=[
                ('welfare_id', models.AutoField(primary_key=True, serialize=False)),
                ('welfaretitle', models.CharField(max_length=50)),
                ('welfarepurpose', models.CharField(max_length=250)),
                ('welfare', models.CharField(max_length=50)),
                ('welfaredate', models.DateField()),
                ('amount', models.FloatField()),
                ('creditedby', models.CharField(max_length=50)),
                ('welfarestatus', models.CharField(max_length=50)),
            ],
        ),
    ]
