# Generated by Django 4.1 on 2025-01-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_tbl_welfare'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_member',
            name='memberclass',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_welfare',
            name='welfare',
            field=models.CharField(max_length=500),
        ),
    ]
