# Generated by Django 4.1 on 2025-01-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_tbl_member_memberclass_alter_tbl_welfare_welfare'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notificationtitle', models.CharField(max_length=100)),
                ('notificationdescription', models.CharField(max_length=500)),
                ('data', models.CharField(max_length=500)),
                ('expirydate', models.DateField()),
                ('notificationstatus', models.CharField(max_length=50)),
            ],
        ),
    ]
