# Generated by Django 4.1 on 2025-02-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_tbl_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_member',
            name='membercode',
            field=models.IntegerField(default=0),
        ),
    ]
