# Generated by Django 4.1 on 2025-02-12 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_tbl_member_membercode'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_welfarepublish',
            fields=[
                ('welfarepublish_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_member')),
                ('welfare_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_welfare')),
            ],
        ),
    ]
