# Generated by Django 4.1 on 2025-02-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_tbl_welfarepublish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_notification',
            name='data',
        ),
        migrations.AddField(
            model_name='tbl_notification',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
