from django.urls import path
from . import views
from .views import ExportExcelLoan
from .views import ExportExcelLoantransaction
from .views import member_details_view
urlpatterns=[
    path('index/',views.index,name="index"),
    path('district',views.district,name="district"),
    path('district_process',views.district_process,name="district_process"),
    path('location',views.location,name="location"),
    path('location_process',views.location_process,name="location_process"),
    path('unit',views.unit,name="unit"),
    path('unit_process',views.unit_process,name="unit_process"),
    path('viewdistrict',views.viewdistrict,name="viewdistrict"),
    path('viewlocation',views.viewlocation,name="viewlocation"),
    path('filllocation',views.filllocation,name="filllocation"),
    path('viewunit',views.viewunit,name="viewunit"),
    path('fillunit',views.fillunit,name="fillunit"),
    path('deletedistrict/<district_id>',views.deletedistrict,name="deletedistrict"),
    path('deletelocation/<location_id>',views.deletelocation,name="deletelocation"),
    path('deleteunit/<unit_id>',views.deleteunit,name="deleteunit"),
    path('memberreg/',views.memberreg,name="memberreg"),
    path('memberreg_process',views.memberreg_process,name="memberreg_process"),
    path('viewmember',views.viewmember,name="viewmember"),
    path('deletemember/<memberid>',views.deletemember,name="deletemember"),
    path('welfarereg/',views.welfarereg,name="welfarereg"),
    path('welfare_process',views.welfare_process,name="welfare_process"),
    path('verification/',views.verification,name="verification"),
    path('verificationaccept/<login_id>',views.verificationaccept,name="verificationaccept"),
    path('verificationreject/<login_id>',views.verificationreject,name="verificationreject"),
    path('notification/',views.notification,name="notification"),
    path('notification_process/',views.notification_process,name="notification_process"),
    path('loanverification/',views.loanverification,name="loanverification"),
    path('loanverificationaccept/<id>',views.loanverificationaccept,name="loanverificationaccept"),
    path('loanverificationreject/<id>',views.loanverificationreject,name="loanverificationreject"),
    path('acceptedloan',views.acceptedloan,name="acceptedloan"),
    path('viewwelfare',views.viewwelfare,name="viewwelfare"),
    path('publishwelfare/<id>', views.publishwelfare, name='publishwelfare'),
    path('fill_members/', views.fill_members, name='fill_members'),
    path('publish_process/', views.publish_process, name='publish_process'),
    path('inactive_welfare/<id>',views.inactive_welfare,name="inactive_welfare"),
    path('editdistrict/<district_id>',views.editdistrict,name="editdistrict"),
    path('editlocation/<location_id>',views.editlocation,name="editlocation"),
    path('editunit/<unit_id>',views.editunit,name="editunit"),
    path('viewloanpayment/',views.viewloanpayment,name="viewloanpayment"),
    path('dashboard/',views.dashboard,name="dashboard"),
    path('edit_welfare/<welfare_id>',views.edit_welfare,name="edit_welfare"),
    path('viewnotification/',views.viewnotification,name="viewnotification"),
    path('inactive_notification/<id>',views.inactive_notification,name="inactive_notification"),
    path('edit_notification/<notification_id>',views.edit_notification,name="edit_notification"),
    path('pie_chart',views.pie_chart,name="pie_chart"),
    path('export_excel/', ExportExcelLoan.as_view(), name='export_excel'),
    path('export_excel1/', ExportExcelLoantransaction.as_view(), name='export_excel1'),
    path('admin/member-details/', member_details_view, name='member_details'),
    path('deposit_bar_chart/', views.deposit_bar_chart, name='deposit_bar_chart'),
    path('loan_transaction_area_chart/', views.loan_transaction_area_chart, name='loan_transaction_area_chart'),
    path('publishedwelfare/', views.publishedwelfare, name='publishedwelfare'),
    path('viewwelfarepayment/',views.viewwelfarepayment,name="viewwelfarepayment"),
    path('total_deposit_view/',views.total_deposit_view,name="total_deposit_view"),
]

