# Generated by Django 4.1 on 2025-01-25 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0008_tbl_member_memberclass_alter_tbl_welfare_welfare'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_deposite',
            fields=[
                ('deposite_id', models.AutoField(primary_key=True, serialize=False)),
                ('depositedate', models.DateField()),
                ('matureddate', models.DateField()),
                ('interestrate', models.FloatField()),
                ('matuedamount', models.FloatField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_member')),
            ],
        ),
    ]
