# Generated by Django 4.1 on 2025-01-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_deposite',
            name='deposite',
            field=models.FloatField(default=0),
        ),
    ]
