# Generated by Django 4.1 on 2025-01-27 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_tbl_member_memberclass_alter_tbl_welfare_welfare'),
        ('memberapp', '0002_tbl_deposite_deposite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_deposite',
            name='deposite',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='tbl_loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('monthlyinterest', models.FloatField()),
                ('monthlyamount', models.FloatField()),
                ('loanstatus', models.CharField(max_length=20)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_member')),
            ],
        ),
    ]
