# Generated by Django 4.1 on 2025-01-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0003_alter_tbl_deposite_deposite_tbl_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_deposite',
            name='depositedate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
