# Generated by Django 4.1 on 2025-01-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0004_alter_tbl_deposite_depositedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_loan',
            name='installmentpolicy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tbl_loan',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
