# Generated by Django 4.1 on 2025-01-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0005_tbl_loan_installmentpolicy_alter_tbl_loan_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_loan',
            old_name='installmentpolicy',
            new_name='installmentmonths',
        ),
    ]
