# Generated by Django 4.1 on 2025-02-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0006_rename_installmentpolicy_tbl_loan_installmentmonths'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_loan',
            name='memberclass',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
