# Generated by Django 4.1 on 2025-02-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0007_tbl_loan_memberclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_loan',
            name='memberclass',
        ),
    ]
