# Generated by Django 4.1 on 2025-02-14 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_tbl_welfarepublish'),
        ('memberapp', '0008_remove_tbl_loan_memberclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_welfaretransaction',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('welfareamount', models.FloatField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_member')),
                ('welfare_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_welfare')),
            ],
        ),
    ]
