# Generated by Django 4.1 on 2025-02-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0009_tbl_welfaretransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_loan',
            name='approveddate',
            field=models.DateField(null=True),
        ),
    ]
