# Generated by Django 4.1 on 2025-02-21 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0010_tbl_loan_approveddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_loantransaction',
            fields=[
                ('loantrans_id', models.AutoField(primary_key=True, serialize=False)),
                ('paiddate', models.DateField(auto_now_add=True)),
                ('loanamount', models.FloatField()),
                ('amount', models.FloatField()),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberapp.tbl_loan')),
            ],
        ),
    ]
