# Generated by Django 4.1 on 2025-02-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0011_tbl_loantransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_loantransaction',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
