# Generated by Django 4.1 on 2025-03-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0012_tbl_loantransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_loan',
            name='balanceamount',
            field=models.FloatField(null=True),
        ),
    ]
