# Generated by Django 4.1 on 2025-03-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0013_tbl_loan_balanceamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_loantransaction',
            name='fine',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_loantransaction',
            name='paidduedate',
            field=models.DateField(null=True),
        ),
    ]
