# Generated by Django 4.1 on 2025-03-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberapp', '0014_tbl_loantransaction_fine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_deposite',
            name='interestrate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_deposite',
            name='matuedamount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_deposite',
            name='matureddate',
            field=models.DateField(null=True),
        ),
    ]
